apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    resource_kind: '*v1.Secret'
  name: bookinfo-client
  namespace: bookinfo
data:
  oauth: Y2xpZW50U2VjcmV0OiBjbGllbnQtc2VjcmV0Cg==
