apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: global-limit
  namespace: bookinfo
spec:
  raw:
    descriptors:
    - key: generic_key
      value: count
      rateLimit:
        requestsPerUnit: 20
        unit: MINUTE
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: count

