apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: bookinfo
  namespace: bookinfo
spec:
  sslConfig:
    secretRef:
      name: bookinfo-tls
      namespace: bookinfo
  virtualHost:
    domains:
    - 'bookinfo.104-154-163-0.nip.io'
    options:
      extauth:
        configRef:
          name: bookinfo-oauth
          namespace: bookinfo
      rateLimitConfigs:
        refs:
        - name: global-limit
          namespace: bookinfo
      waf:
        customInterventionMessage: 'Username should only contain letters'
        ruleSets:
        - ruleStr: |
            # Turn rule engine on
            SecRuleEngine On
            SecRule ARGS:/username/ "[^a-zA-Z]" "t:none,phase:2,deny,id:6,log,msg:'allow only letters in username'"
      transformations:
        responseTransformation:
          transformationTemplate:
            parseBodyBehavior: DontParse
            body:
              text: '{% if header(":status") == "429" %}<html><body style="background-color:powderblue;"><h1>Too many Requests!</h1><p>Try again after 10 seconds</p></body></html>{% else %}{{ body() }}{% endif %}'
    routes:
    - matchers:
        - prefix: /
      routeAction:
        multi:
          destinations:
          - weight: 5
            destination:
              upstream:
                name: productpage
                namespace: bookinfo
          - weight: 5
            destination:
              upstream:
                name: productpage-beta
                namespace: bookinfo-beta
