apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: httpbin
  namespace: httpbin
spec:
  kube:
    selector:
      app: httpbin
    serviceName: httpbin
    serviceNamespace: httpbin
    servicePort: 8000
