apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: httpbin
spec:
  virtualHost:
    domains:
    - 'httpbin.104-154-163-0.nip.io'
    options:
      extauth:
        configRef:
          name: httpbin-oauth
          namespace: httpbin
      # extract id token
      stagedTransformations:
        early:
          requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  extractors:
                    token:
                      header: 'cookie'
                      regex: 'id_token=(.*); .*'
                      subgroup: 1
                  headers:
                    jwt:
                      text: '{{ token }}'
      # remove cookie header
      headerManipulation:
        requestHeadersToRemove:
        - "cookie"
    routes:
    - matchers:
        - prefix: /
      routeAction:
        single:
          upstream:
            name: httpbin
            namespace: httpbin
