apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: httpbin
spec:
  virtualHost:
    domains:
    - 'httpbin.104-154-163-0.nip.io'
    options:
      extauth:
        configRef:
          name: httpbin-oauth
          namespace: httpbin
      # extract id token
      stagedTransformations:
        early:
          requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  extractors:
                    token:
                      header: 'cookie'
                      regex: 'id_token=(.*); .*'
                      subgroup: 1
                  headers:
                    jwt:
                      text: '{{ token }}'
      # remove cookie header
      headerManipulation:
        requestHeadersToRemove:
        - "cookie"
      jwt:
        providers:
          keycloak:
            issuer: http://idp.104-154-163-0.nip.io/auth/realms/default
            tokenSource:
              headers:
              - header: Jwt
            claimsToHeaders:
            - claim: email
              header: x-solo-claim-email
            - claim: email_verified
              header: x-solo-claim-email-verified
            jwks:
              remote:
                url: http://idp.104-154-163-0.nip.io/auth/realms/default/protocol/openid-connect/certs
                upstreamRef:
                  name: keycloak
                  namespace: gloo-system
      rbac:
        policies:
          viewer:
            permissions:
              methods:
              - GET
              pathPrefix: /get
            principals:
            - jwtPrincipal:
                claims:
                  email: user1@solo.io
    routes:
    - matchers:
        - prefix: /
      routeAction:
        single:
          upstream:
            name: httpbin
            namespace: httpbin
