apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: productpage-beta
  namespace: bookinfo-beta
spec:
  kube:
    selector:
      app: productpage
    serviceName: productpage
    serviceNamespace: bookinfo-beta
    servicePort: 9080
